baseurl = "https://www.christophflick.de/"
title = "Christoph Flick"
description = "This is the personal webspace of Christoph Flick, a german software engineer and current master's degree student of Digital Transformation."
copyright = "Copyright &copy; 2020 - Christoph Flick | [Impressum & Datenschutz](/impressum)"
canonifyurls = true
theme = "hugo-kiera"

paginate = 3

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true

# Note: to disable a social network icon delete or comment out the corresponding line
[author]
    name = "Christoph Flick"
    github = "ChFlick"
    gitlab = "ChFlick"
    linkedin = "christoph-flick"
    email = "hi (at) christophflick.de"
    xing = "Christoph_Flick2"
    #facebook = "username"
    #twitter = "ds_says"
    #instagram = "username"
    #stackoverflow = "username"
    #youtube = "user/username" # or channel/channelname

[params]
    tagline = "A webspace with not yet known information"
    description = "This is the personal webspace of Christoph Flick, a german software engineer and current master's degree student of Digital Transformation."
    #images = [""] #This is used for opengraph/twitter cards.
    customCSS = ["css/klaro.css"]  #Optional Customised CSS
    #favicon = ""

# uncomment to enable the Tags link on the main toolbar
#  [[menu.main]]
#    identifier = "tags"
#    name = "Tags"
#    url = "/tags"
#    weight = 1

# uncomment to enable the Categories link on the main toolbar
#  [[menu.main]]
#    identifier = "categories"
#    name = "Categories"
#    url = "/categories"
#    weight = 1
